title: Home Automation Cookbook
description: Useful automations and configuration for Home Assistant
email: martin@mgrayson.co.uk
github_username: martingrayson
theme: minima

plugins:
  - jekyll-feed